name: CI

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Run shfmt
        run: make shfmt-docker
      - name: Run ShellCheck
        run: make shellcheck-docker
      - name: Run tests
        run: make test-docker
